version: '2.1'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --bind_ip_all --logpath=/dev/null # --quiet

  web:
    build: .
    links:
      - mongodb
    container_name: githubapi
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGODB_PORT=27017
      - MONGODB_SCHEMA=githubapi
      - MONGODB_HOST=mongodb
      - LOG_LEVEL=INFO
    depends_on:
      - mongodb